### ISSUE TITLE
Android登录点击没反应

### ISSUE THREAD

**Issue by nanasheng** [reactnativecn/react-native-wx#14]
微信没登录会跳转到微信登录界面，登录之后跳转回应用，再次点击微信登录没反应

**Comment by America-first-melon** [comment]
同样的问题  请问是否解决了

**Comment by nanasheng** [comment]
安卓要去微信开放平台设置签名

**Comment by America-first-melon** [comment]
我设置了签名还是这样   求指导 /抱拳

**Comment by nanasheng** [comment]
假如iOS没问题的话 安卓是调试包要用调试包的签名 离线包要用离线包的签名@America-first-melon

**Comment by America-first-melon** [comment]
@nanasheng   好了 弄得离线包的签名 而且包名是ctrl+v过去的才行   多谢指导！
