### ISSUE TITLE
分享没有回调嘛

### ISSUE THREAD

**Issue by lekenny** [reactnativecn/react-native-wx#21]
android分享成功后好像是没有回调的

**Comment by zhangmingnjun** [comment]
你的问题解决了吗，我这边接入测试的时候也是有这个现象的，不知道怎么解决

**Comment by TrustTheBoy** [comment]
@lekenny @zhangmingnjun 你们的解决没？

**Comment by zhangmingnjun** [comment]
@TrustTheBoy 作者提供了解决办法，你去看看就知道了

**Comment by BonnieWeb** [comment]
在哪儿看解决办法 啊？我怎么没找到？求晒

**Comment by BonnieWeb** [comment]
@zhangmingnjun 请问这个解决方法在哪儿啊？我怎么没找到

**Comment by zhangmingnjun** [comment]
https://github.com/reactnativecn/react-native-wx/pull/38
看看吧😄


 在2017年8月4日 13:45:18, BonnieWeb <notifications@github.com> 写道：



在哪儿看解决办法 啊？我怎么没找到？求晒

**Comment by HHuiHao** [comment]
@zhangmingnjun 有解决吗？Android没解决吧

**Comment by maagee** [comment]
只有iOS的解决方法，没有Android的啊
