### ISSUE TITLE
run-android报错

### ISSUE THREAD

**Issue by Gaaaga** [reactnativecn/react-native-wx#28]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#WX_APPID@value at AndroidManifest.xml:18:9-20:43 requires a placeholder substitution but no value for <WX_APPID> is provided.

run-android 报这个错

**Comment by sunnylqm** [comment]
Android配置

在android/app/build.gradle里，defaultConfig栏目下添加如下代码：
```
manifestPlaceholders = [
    // 如果有多项，每一项之间需要用逗号分隔
    WX_APPID: "微信的APPID"      //在此修改微信APPID
]
```
