### ISSUE TITLE
WechatAPI.login 问题

### ISSUE THREAD

**Issue by StarksJohn** [reactnativecn/react-native-wx#7]
WechatAPI.login(config) 返回的 {
    "code": "",
    "appid": "",
    "lang": "",
    "country": "",
} 后, 我自己是不是 还得 写一个 网络请求 以下链接获取access_token：
https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code

**Comment by HiZhenyu** [comment]
提交到服务器端进行处理，不在客户端进行

**Comment by tdzl2003** [comment]
Secret是不宜暴露给客户端的，所以在服务端进行这个处理方才恰当。
